# Site settings
title: Livin La Vida Coding
header-img: img/home-bg.png
email: aisayo@icloud.com
copyright_name: aisayo
description: > # this means to ignore newlines until "baseurl:"
  trying to figure this out 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  aisayo
learn_profile: aisayo
email_username: aisayo@icloud.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
